---
- name: instalar openvpn 
  hosts: virtual
  user: jcuello
  become: yes
  become_method: su
  tasks:
    - name: install epel-release
      yum: name=epel-release state=latest
    - name: upgrade all packages
      yum: name=* state=latest
    - name: install openvpn
      yum: name=openvpn state=latest
    - name: download easyrsa 
      get_url:
        url: https://github.com/OpenVPN/easy-rsa-old/archive/2.3.3.tar.gz
        dest: /tmp/easyrsa
    - name: create directory
      file:
        path: /etc/openvpn/easy-rsa
        state: directory
    - name: extract easyrsa
      unarchive:
        src: /tmp/easyrsa
        dest: /etc/openvpn/easy-rsa
        remote_src: yes
